name: CI

on:
  push:
  pull_request:

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  test:
    name: Tree-sitter tests
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Clone nvim help files
        uses: actions/checkout@v4
        with:
          repository: neovim/neovim
          path: examples/neovim
          sparse-checkout: runtime/doc/
      - name: Set up tree-sitter
        uses: tree-sitter/setup-action/cli@v1
      - name: Run parser tests
        uses: tree-sitter/parser-test-action@v2
      - name: Parse sample files
        uses: tree-sitter/parse-action@v4
        if: runner.os != 'Windows'
        with:
          files: |-
            examples/neovim/runtime/doc/*
            !examples/neovim/runtime/doc/remote_plugin.txt
          # FIXME: these should not have errors
          invalid-files: |-
            examples/neovim/runtime/doc/builtin.txt
            examples/neovim/runtime/doc/change.txt
            examples/neovim/runtime/doc/cmdline.txt
            examples/neovim/runtime/doc/dev_style.txt
            examples/neovim/runtime/doc/dev_tools.txt
            examples/neovim/runtime/doc/develop.txt
            examples/neovim/runtime/doc/editing.txt
            examples/neovim/runtime/doc/eval.txt
            examples/neovim/runtime/doc/fold.txt
            examples/neovim/runtime/doc/ft_ada.txt
            examples/neovim/runtime/doc/ft_hare.txt
            examples/neovim/runtime/doc/ft_ps1.txt
            examples/neovim/runtime/doc/helphelp.txt
            examples/neovim/runtime/doc/if_perl.txt
            examples/neovim/runtime/doc/if_pyth.txt
            examples/neovim/runtime/doc/if_ruby.txt
            examples/neovim/runtime/doc/index.txt
            examples/neovim/runtime/doc/intro.txt
            examples/neovim/runtime/doc/job_control.txt
            examples/neovim/runtime/doc/luaref.txt
            examples/neovim/runtime/doc/map.txt
            examples/neovim/runtime/doc/mbyte.txt
            examples/neovim/runtime/doc/motion.txt
            examples/neovim/runtime/doc/nvim.txt
            examples/neovim/runtime/doc/options.txt
            examples/neovim/runtime/doc/pattern.txt
            examples/neovim/runtime/doc/pi_gzip.txt
            examples/neovim/runtime/doc/pi_msgpack.txt
            examples/neovim/runtime/doc/pi_netrw.txt
            examples/neovim/runtime/doc/pi_paren.txt
            examples/neovim/runtime/doc/pi_tar.txt
            examples/neovim/runtime/doc/pi_tutor.txt
            examples/neovim/runtime/doc/pi_zip.txt
            examples/neovim/runtime/doc/provider.txt
            examples/neovim/runtime/doc/quickfix.txt
            examples/neovim/runtime/doc/quickref.txt
            examples/neovim/runtime/doc/repeat.txt
            examples/neovim/runtime/doc/russian.txt
            examples/neovim/runtime/doc/starting.txt
            examples/neovim/runtime/doc/syntax.txt
            examples/neovim/runtime/doc/tabpage.txt
            examples/neovim/runtime/doc/tips.txt
            examples/neovim/runtime/doc/ui.txt
            examples/neovim/runtime/doc/usr_02.txt
            examples/neovim/runtime/doc/usr_03.txt
            examples/neovim/runtime/doc/usr_07.txt
            examples/neovim/runtime/doc/usr_11.txt
            examples/neovim/runtime/doc/usr_12.txt
            examples/neovim/runtime/doc/usr_22.txt
            examples/neovim/runtime/doc/usr_28.txt
            examples/neovim/runtime/doc/usr_41.txt
            examples/neovim/runtime/doc/various.txt
            examples/neovim/runtime/doc/vim_diff.txt
            examples/neovim/runtime/doc/visual.txt
            examples/neovim/runtime/doc/windows.txt
